name: Manual Deploy

on:
  workflow_dispatch:

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ruby --version
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.3p62
      - uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
